import { interpolate, useCurrentFrame, useVideoConfig } from "remotion";
import type { EndCardProps } from "@crammer/schema";
import { theme } from "../theme";
import { Frame, Kicker, Rule, Safe } from "../components/Frame";
import { fadeIn } from "../components/animate";

/**
 * Sources and image credits. Generated by the pipeline from the storyboard, never
 * chosen by the model — accuracy is the product, so the citations always ship.
 *
 * Long lists scroll slowly rather than shrinking below a readable size.
 */
export const EndCard: React.FC<EndCardProps> = ({ title, sources, credits }) => {
  const frame = useCurrentFrame();
  const { durationInFrames } = useVideoConfig();

  const rows = Math.max(sources.length, credits.length);
  // Only scroll when the content genuinely overflows the safe area.
  const overflow = Math.max(0, rows - 9) * theme.space(6);
  const scroll = interpolate(frame, [30, Math.max(durationInFrames - 20, 40)], [0, overflow], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });

  return (
    <Frame surface="ink">
      <Safe style={{ gap: theme.space(4), overflow: "hidden" }}>
        <div style={{ opacity: fadeIn(frame, 0, 12) }}>
          <Kicker tone="onInk">{title}</Kicker>
          <div style={{ marginTop: theme.space(2) }}>
            <Rule />
          </div>
        </div>

        <div
          style={{
            display: "grid",
            gridTemplateColumns: "1.15fr 1fr",
            gap: theme.space(10),
            transform: `translateY(${-scroll}px)`,
            opacity: fadeIn(frame, 6, 16),
          }}
        >
          <section>
            <h2 style={headingStyle}>Sources</h2>
            <ol style={listStyle}>
              {sources.map((source, i) => (
                <li key={source.id} style={itemStyle}>
                  <span style={{ color: theme.color.accent, fontVariantNumeric: "tabular-nums" }}>
                    {String(i + 1).padStart(2, "0")}{" "}
                  </span>
                  <span style={{ color: theme.color.onInk }}>{source.title}</span>
                  <span style={{ color: theme.color.onInkMuted }}> — {source.publisher}</span>
                </li>
              ))}
            </ol>
          </section>

          <section>
            <h2 style={headingStyle}>Images</h2>
            <ul style={listStyle}>
              {credits.map((credit) => (
                <li key={credit.contentHash} style={{ ...itemStyle, color: theme.color.onInkMuted }}>
                  {credit.attribution}
                </li>
              ))}
              {credits.length === 0 ? (
                <li style={{ ...itemStyle, color: theme.color.onInkMuted }}>
                  No photography used.
                </li>
              ) : null}
            </ul>
          </section>
        </div>
      </Safe>
    </Frame>
  );
};

const headingStyle: React.CSSProperties = {
  margin: `0 0 ${theme.space(2)}px`,
  fontSize: theme.size.subheading,
  fontWeight: theme.font.weight.bold,
  letterSpacing: theme.font.tracking.heading,
  color: theme.color.onInk,
  paddingBottom: theme.space(2),
  borderBottom: `${theme.stroke.hairline}px solid ${theme.color.lineOnInk}`,
};

const listStyle: React.CSSProperties = {
  listStyle: "none",
  margin: 0,
  padding: 0,
  display: "flex",
  flexDirection: "column",
  gap: theme.space(1.5),
};

const itemStyle: React.CSSProperties = {
  fontSize: theme.size.caption,
  lineHeight: theme.lineHeight.normal,
  letterSpacing: theme.font.tracking.body,
};
