import type { ImageAsset, ImageSlot } from "@crammer/schema";

/**
 * Fixture assets point at the placeholder images in `public/images`, generated by
 * `pnpm --filter @crammer/video gen:fixtures`. Attribution strings are deliberately
 * marked as fixtures so they can never be confused with a real credit.
 */
export function fixtureAsset(name: string, hash: string): ImageAsset {
  return {
    localPath: `images/${name}.jpg`,
    sourceUrl: "https://commons.wikimedia.org/wiki/Main_Page",
    pageUrl: "https://commons.wikimedia.org/wiki/Main_Page",
    author: "Crammer fixtures",
    licence: "cc0",
    licenceUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    attribution: "Placeholder image (fixture), CC0",
    provider: "wikimedia",
    width: 1920,
    height: 1080,
    contentHash: hash,
  };
}

export function fixtureSlot(name: string, hash: string, alt: string): ImageSlot {
  return { queries: [alt], alt, asset: fixtureAsset(name, hash) };
}
