/**
 * Generates src/geo/iso.ts — an ISO 3166-1 alpha-3 -> numeric lookup.
 *
 * world-atlas TopoJSON identifies countries by numeric code, but storyboards use
 * alpha-3 because that is what an LLM reliably produces. Generating the table once and
 * committing it keeps `i18n-iso-countries` out of the render bundle.
 *
 * Run with: pnpm --filter @crammer/video gen:iso
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import countries from "i18n-iso-countries";

const alpha3 = countries.getAlpha3Codes();
const entries: [string, string][] = [];

for (const code of Object.keys(alpha3)) {
  const numeric = countries.alpha3ToNumeric(code);
  if (!numeric) continue;
  entries.push([code, numeric.padStart(3, "0")]);
}
entries.sort(([a], [b]) => a.localeCompare(b));

const body = entries.map(([a, n]) => `  ${a}: "${n}",`).join("\n");

const file = `/**
 * GENERATED by scripts/gen-iso.ts — do not edit by hand.
 * ISO 3166-1 alpha-3 -> numeric, matching the ids in world-atlas TopoJSON.
 */
export const ISO3_TO_NUMERIC: Record<string, string> = {
${body}
};

export const NUMERIC_TO_ISO3: Record<string, string> = Object.fromEntries(
  Object.entries(ISO3_TO_NUMERIC).map(([a3, num]) => [num, a3]),
);

export function iso3ToNumeric(code: string): string | undefined {
  return ISO3_TO_NUMERIC[code.toUpperCase()];
}
`;

const out = join(dirname(fileURLToPath(import.meta.url)), "..", "src", "geo", "iso.ts");
writeFileSync(out, file);
console.log(`Wrote ${entries.length} country codes to ${out}`);
