import { writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { FactCheckReport, RunCost, Storyboard } from "@crammer/schema";

/** The narration as plain text, scene by scene. */
export function transcriptText(storyboard: Storyboard): string {
  const lines = [storyboard.title, "=".repeat(storyboard.title.length), ""];
  for (const scene of storyboard.scenes) {
    if (scene.narration.trim().length === 0) continue;
    lines.push(scene.narration.trim(), "");
  }
  return lines.join("\n");
}

/**
 * Sources and image credits, as Markdown.
 *
 * This ships with every video. A claim a viewer cannot trace back is a claim Crammer
 * should not have made.
 */
export function sourcesMarkdown(
  storyboard: Storyboard,
  report?: FactCheckReport,
): string {
  const lines: string[] = [`# Sources — ${storyboard.title}`, ""];

  lines.push(`Topic: ${storyboard.topic}`, "", "## References", "");
  if (storyboard.sources.length === 0) {
    lines.push("_No sources recorded._", "");
  }
  for (const [i, source] of storyboard.sources.entries()) {
    const date = source.publishedAt ? `, ${source.publishedAt}` : "";
    lines.push(`${i + 1}. [${source.title}](${source.url}) — ${source.publisher}${date}`);
  }

  lines.push("", "## Image credits", "");
  if (storyboard.credits.length === 0) {
    lines.push("_No photography used._");
  }
  for (const credit of storyboard.credits) {
    const link = credit.pageUrl ?? credit.sourceUrl;
    const licence = credit.licenceUrl ? ` ([licence](${credit.licenceUrl}))` : "";
    lines.push(`- ${credit.attribution}${licence} — [source](${link})`);
  }

  if (report) {
    lines.push("", "## Fact check", "");
    lines.push(`Result: **${report.passed ? "passed" : "failed"}**`, "");
    if (report.balanceNote) lines.push(report.balanceNote, "");
    if (report.issues.length > 0) {
      lines.push("Outstanding notes:", "");
      for (const issue of report.issues) {
        lines.push(`- **${issue.severity}/${issue.kind}** (${issue.sentenceId}): ${issue.explanation}`);
      }
    } else {
      lines.push("No outstanding issues.");
    }
  }

  lines.push("", "---", "", "_Generated by Crammer._", "");
  return lines.join("\n");
}

/** A human-readable cost table for the end of a run. */
export function costTable(cost: RunCost): string {
  const header = ["stage", "in", "out", "cached", "tts chars", "reqs", "pence", "time"];
  const rows = cost.stages.map((s) => [
    s.stage,
    String(s.inputTokens),
    String(s.outputTokens),
    String(s.cacheReadTokens),
    String(s.ttsCharacters),
    String(s.requests),
    s.estimatedPence.toFixed(2),
    `${(s.durationMs / 1000).toFixed(1)}s`,
  ]);
  rows.push([
    "TOTAL",
    "",
    "",
    "",
    "",
    "",
    cost.totalPence.toFixed(2),
    `${(cost.stages.reduce((n, s) => n + s.durationMs, 0) / 1000).toFixed(1)}s`,
  ]);

  const widths = header.map((_, i) =>
    Math.max(header[i]!.length, ...rows.map((r) => r[i]!.length)),
  );
  const line = (cells: string[]) =>
    cells.map((cell, i) => (i === 0 ? cell.padEnd(widths[i]!) : cell.padStart(widths[i]!))).join("  ");

  return [
    line(header),
    widths.map((w) => "-".repeat(w)).join("  "),
    ...rows.map(line),
    "",
    "Costs are estimates. Check current provider pricing before relying on them.",
  ].join("\n");
}

/** Writes transcript.txt and sources.md next to the video. */
export async function writeRunOutputs(
  outDir: string,
  storyboard: Storyboard,
  report?: FactCheckReport,
): Promise<void> {
  await writeFile(join(outDir, "transcript.txt"), transcriptText(storyboard));
  await writeFile(join(outDir, "sources.md"), sourcesMarkdown(storyboard, report));
}
