/**
 * Copies the variables the web app needs from the repo-root `.env` into
 * `apps/web/.env.local`.
 *
 * Next.js only reads env files next to the app, and the CLI, the worker and the web app
 * otherwise share one file. Keeping one source of truth and generating the copy beats
 * maintaining the same keys twice.
 *
 * Run with: pnpm sync:env
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const KEYS = [
  "DATABASE_URL",
  "SUPABASE_URL",
  "SUPABASE_ANON_KEY",
  "SUPABASE_SERVICE_ROLE_KEY",
  "NEXT_PUBLIC_SUPABASE_URL",
  "NEXT_PUBLIC_SUPABASE_ANON_KEY",
  "NEXT_PUBLIC_SITE_URL",
  "ANTHROPIC_API_KEY",
  "ANTHROPIC_WORKSPACE_ID",
  "CRAMMER_MODEL",
  "WIKIMEDIA_USER_AGENT",
  "ELEVENLABS_API_KEY",
  "ELEVENLABS_VOICE_ID",
  "UNSPLASH_ACCESS_KEY",
  "PEXELS_API_KEY",
  "TRIGGER_SECRET_KEY",
  "RESEND_API_KEY",
  "CRAMMER_MEDIA_ROOT",
];

const root = process.cwd();
const source = readFileSync(join(root, ".env"), "utf8");

const lines = [
  "# Generated by `pnpm sync:env` from the repo-root .env — do not edit by hand.",
  "",
];
const seen = new Set<string>();

for (const line of source.split("\n")) {
  const key = /^([A-Z0-9_]+)=/.exec(line)?.[1];
  if (key && KEYS.includes(key)) {
    lines.push(line);
    seen.add(key);
  }
}

// The local artefact store needs an absolute path, and the repo root is the one place
// that knows it.
if (!seen.has("CRAMMER_MEDIA_ROOT")) lines.push(`CRAMMER_MEDIA_ROOT="${join(root, "out", "web")}"`);

writeFileSync(join(root, "apps", "web", ".env.local"), `${lines.join("\n")}\n`);
console.log(`Wrote apps/web/.env.local with ${seen.size + 1} variables.`);
